config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :grandmas, only: [:index, :show, :new, :create, :destroy] do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:index, :update]

  resources :users, only: [:show, :new, :create, :destroy]

  # get "components-julia", to: "pages#components_julia"

  # get '/components_alex' => 'pages#components_alex'

  # get "/components_alexander/", to: "pages#components_alexander"

  # get "/components_jorgen/", to: "pages#components_jorgen"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :grandma
  belongs_to :user
  validates :start_time, :end_time, :date, presence: true
end

app/models/grandma.rb
class Grandma < ApplicationRecord
  validates :first_name, :last_name, :address, presence: true
  validates :description, length: { minimum: 10 }
  has_many :bookings
  belongs_to :user
  has_many_attached :photo_url
  # validates :photo_url, limit: { min: 1, max: 3 }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
  against: [ :first_name, :last_name, :description ],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
  validates :address, presence: true
  has_many :grandmas
  has_many :bookings
  has_one_attached :profile_photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :address, :profile_photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :address, :profile_photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

   def show
    @booking = Booking.find(params[:id])
  end

  def new
    @user = current_user
    @grandmas = Grandma.all
    @grandma = Grandma.find(params[:grandma_id])
    @booking = Booking.new
  end

  def create
    @user = current_user
    @grandma = Grandma.find(params[:grandma_id])
    @booking = Booking.new(booking_params)
    @booking.user = @user
    @booking.grandma = @grandma
    @price = (@booking.end_time - @booking.start_time)/3600*@booking.grandma.hourly_rate
    @booking.price = @price
    if @booking.save
      redirect_to user_path(@user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @user = current_user
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to user_path(@user)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :end_time, :date, :status)
  end
end

app/controllers/grandmas_controller.rb
class GrandmasController < ApplicationController
  def index
    if params[:query].present?
      sql_query = <<~SQL
        grandmas.first_name @@ :query
        OR grandmas.last_name @@ :query
        OR grandmas.description @@ :query
      SQL
      @grandmas = Grandma.where(sql_query, query: "%#{params[:query]}%")
    else
      @grandmas = Grandma.all
    end
    @markers = @grandmas.geocoded.map do |grandma|
      {
        lat: grandma.latitude,
        lng: grandma.longitude,
        image_url: helpers.asset_url("granny-pin.png")
      }
    end
  end

  def show
    @grandma = Grandma.find(params[:id])
    @booking = Booking.new
    @markers = Grandma.where(id: params[:id]).geocoded.map do |grandma|
      {
        lat: grandma.latitude,
        lng: grandma.longitude,
        image_url: helpers.asset_url("granny-pin.png")
      }
    end
  end

  def new
    @grandma = Grandma.new
  end

  def create
    @user = current_user
    @grandma = Grandma.new(grandma_params)
    @grandma.user = @user

    if @grandma.save
      redirect_to grandma_path(@grandma)
    else
      render :new
    end
  end

  def destroy
  end

  private

  def grandma_params
    params.require(:grandma).permit(:first_name, :last_name, :address, :description, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @grandmas = Grandma.all
  end


  def components_julia
  end

  def components_alex
    @grandma = Grandma.new
  end

  def components_alexander
    @grandma = Grandma.new
  end

  def components_jorgen
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def show
    @user = current_user
    @grandmas = @user.grandmas
    @host_bookings = Booking.where(grandma: @grandmas)
  end

  def create
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:profile_photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="everything">
	<div class="links-card">
		<div class="new-booking-card">
		<h2>Book <%= @grandma.first_name %> now!</h2>
		<%= cl_image_tag @grandma.photo_url[0].key %>
			<div class="card-text">
				<ul>
					<li><%= @grandma.first_name %> <%= @grandma.last_name %></li>
					<li><%= @grandma.address %></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="middel-card">
		<div class="pay-form">
			<p class="text">Please pay here:</p>
			<div class="centre-content">
				<h1 class="price"><span>€<%= @grandma.hourly_rate %>/h</span></h1>
				<p class="course">
				Rent the perfect grandma now !
				</p>
			</div>

			<div class="last-content">
				<button type="button" class="button-secondary">
				WePay
				</button>
				<button type="button" class="button-secondary">
				PayPal
				</button>
			</div>

			<div class="form-inputs">
				<p>Pay using Credit or Debit card</p>

				<div class="card-number">
				<label class="label-pay"> Card Number </label>
				<input
					type="text"
					class="form-select mx-1 date required"
					placeholder="###-###-###"/>
				</div>
				<div class="date-number">
				<label class="label-pay"> Expiry Date </label>
				<input type="text" class="form-select mx-1 date required"
						placeholder="DD-MM-YY" />
				</div>

				<div class="cvv-number">
				<label class="label-pay"> CVV number </label>
				<input type="text" class="form-select mx-1 number required"
						placeholder="xxx" />
				</div>
				<div class="nameholder-number">
				<label class="label-pay"> Card Holder name </label>
				<input
					type="text"
					class="form-select mx-1 date required"
					placeholder="Enter your Name"/>
				</div>
			</div>
		</div>
	</div>
	<div class="right-card">
				<%= simple_form_for [@grandma, @booking] do |f| %>
	        <%= f.error_notification %>
	        <h3 class="booking_form_title">Booking details</h3>
	        <div class="form-inputs">
	          <%= f.input :date, as: :date, html5: true, label: "Date", input_html: {value: params[:new_booking][:date]}%>
	          <%= f.input :start_time, as: :time, html5: true, label: "Start time"%>
	          <%= f.input :end_time, as: :time, html5: true, label: "End time"%>
	         </div>
	         
	          <div class="form-actions">
	            <%= f.button :submit, "Book" %>
	          </div>
		     <% end %>
		     <p><%=  %></p>
 </div>
</div>

app/views/grandmas/index.html.erb
<div class="granny-grid-container">
	<div class="left-card">

	<% @grandmas.each do |grandma| %>
		<a class="link-wrapper" href="grandmas/<%= grandma.id %>">
			<div class="main-card">
				<div class="pic-size">
					<%= cl_image_tag grandma.photo_url[0].key %>
				</div>
				<div class="card-text">
				  <h3><%= "#{grandma.first_name} #{grandma.last_name} "%></h3>
          <p id="address"><em><%= "#{grandma.address}" %></em></p>
				  <% if grandma.description.length > 30 %>



				  <p><%= "#{grandma.description[0, 100]}..."%></p>

				  <% else %>
				  <p><%= grandma.description %></p>
				  <% end %>
				</div>
			</div>
		</a>

		<% end %>
	</div>

	<div style="width: 100%; height: 100%;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

</div>

app/views/grandmas/new.html.erb
<div class="d-flex flex-row" id="new-div">
  <div id="new-pics">

  </div>
  <div class="create-form">
    <h2>Create a new grandma</h2>
    <%= simple_form_for @grandma do |f| %>
      <%= f.input :first_name, label: false, placeholder: "First name", input_html: { class:"form-input" } %>
      <%= f.input :last_name, label: false, placeholder: "Last name", input_html: { class:"form-input" }  %>
      <%= f.input :address, label: false, placeholder: "Address", input_html: { class:"form-input" }  %>
      <%= f.input :description, label: false, placeholder: "Description", as: :text, input_html: { class:"form-input", :rows => 5 }  %>
      <%= f.input :photo_url, as: :file, input_html: { multiple: true } %>
      <%= f.button :submit, "Create grandma", input_html: { class:"button-primary" }  %>
    <% end %>
  </div>
</div>

<% if flash[:alert] %>
      <div id="alert">
         <%= flash[:alert] %>
      </div>
<% end %>

app/views/grandmas/show.html.erb
<div class="show_container">
  <div class="d-flex justify-content-center show_images">
    <div class="banner_show d-flex flex-row">
    <% if @grandma.photo_url[0].nil? %>
      <div id="banner_show_left" style="background-image:url(https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png)"></div>
        <% else %>
        <div id="banner_show_left" style="background-image:url(<%= cl_image_path @grandma.photo_url[0].key %>)"></div>
        <% end %>
      <div class="banner_show_middle">
      <% if @grandma.photo_url[1].nil? %>
        <div id="middle-top" style="background-image:url(https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png)"></div>
        <% else %>
        <div id="middle-top" style="background-image:url(<%= cl_image_path @grandma.photo_url[1].key %>)"></div>
        <% end %>
         <% if @grandma.photo_url[2].nil? %>
        <div id="middle-bottom" style="background-image:url(https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png)"></div>
        <% else %>
        <div id="middle-bottom" style="background-image:url(<%= cl_image_path @grandma.photo_url[2].key %>)"></div>
        <% end %>
      </div>
      <div id="banner_show_right" style="height: 100%;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
  <div class="lower_show">
      <div class ="show_description">
          <h2><%="#{@grandma.first_name} #{@grandma.last_name}"%></h2>
          <p><%="#{@grandma.description}"%></p>
          <p class="show_rate"><%="€#{@grandma.hourly_rate}/hr"%></p>
      </div>
      <div class="booking_form">
        <%= simple_form_for :new_booking, url: new_grandma_booking_path(@grandma), method: :get do |f| %>
          <%= f.error_notification %>
          <h3 class="booking_form_title">Booking details</h3>
          <div class="form-inputs" data-controller="date">
            <%= f.input :date, as: :date, html5: true, label: "Date" %>
          </div>
            <div class="form-actions">
              <%= f.button :submit, "Book" %>
            </div>
        <% end %>
      </div>
    </div>
</div>

app/views/layouts/_banner.html.erb
<div class="banner" style="background-image: url('  ');">
  <div class="container">
    <h1>Welcome to</h1>
    <h1><em>insta</em>GRAN</h1>
    <div class="banner-buttons d-flex flex-column">
      <%= link_to "sign up", "#", class: "banner-button d-flex justify-content-center align-items-center mt-3 border border-2 border-primary"%>
      <%= link_to "login", "#", class: "banner-button d-flex justify-content-center align-items-center mt-2 border border-2 border-primary" %>
    </div>
  </div>
</div>

app/views/layouts/_banner_show.html.erb
<div class="d-flex justify-content-center">
  <div class="banner_show d-flex flex-row">
    <div id="banner_show_left" class=""></div>
    <div class="banner_show_middle" class="">
      <div id="middle-top"></div>
      <div id="middle-bottom"></div>
    </div>
    <div id="banner_show_right" class=""></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagran</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>

    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>

    <%= yield %>

    <%# <div class="clear"></div> %>
    <div class="footer d-flex justify-content-center">
      <div class="d-flex">
        <div  class="footer-links">
          <%= link_to "home", root_path %>
        </div>
        <div class="footer-links">
          <%= link_to "about us", "#" %>
        </div >
        <div class="footer-links">
          <%= link_to "contact", "#" %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/components_alex.html.erb
<h1>Components</h1>

<div class="main-card">
<img src = "https://media.istockphoto.com/id/1216426253/photo/portrait-of-healthy-african-american-senior-woman.jpg?s=612x612&w=0&k=20&c=pJv9X0QPyKWy8-_NUc2ipYc-shPoE7yYMPS-qair2fM=">
<div class="card-text">
  <h2>Grandma Name</h2>
  <p>Small description of Grandma goes here.</p>
</div>
</div>

<div class="create-form">
<h2>Create a new grandma</h2>
  <%= simple_form_for @grandma do |f| %>
    <%= f.input :first_name, label: false, placeholder: "First name", input_html: { class:"form-input" } %>
    <%= f.input :last_name, label: false, placeholder: "Last name", input_html: { class:"form-input" }  %>
    <%= f.input :address, label: false, placeholder: "Address", input_html: { class:"form-input" }  %>
    <%= f.input :description, label: false, placeholder: "Description", as: :text, input_html: { class:"form-input", :rows => 5 }  %>
    <%= f.button :submit, 'Create profile', class:"button-primary", id:"full-width"  %>
  <% end %>
</div>

<div class="upload-image-grid">
<div class="image-square" id="image-square-one"><p>+</p></div>
<div class="image-square" id="image-square-two"><p>+</p></div>
<div class="image-square" id="image-square-three"><p>+</p></div>
<div class="image-square" id="image-square-four"><p>+</p></div>
</div>

app/views/pages/components_alexander.html.erb
<h1>hello</h1>
<button class="button-primary" role="button">Primary button</button>
<button class="button-secondary" role="button">Secondary button</button>

<div class="booking_form">
  <div class="booking_form">
    <%= simple_form_for @grandma do |f| %>
      <%= f.error_notification %>
      <h3 class="booking_form_title">Booking details</h3>
      <div class="form-inputs">
        <%= f.input :created_at, as: :date, html5: true, label: "Start date"%>
        <%= f.input :created_at, as: :date, html5: true, label: "End date"%>
      </div>
      <div class="form-actions">
        <%= f.button :submit, "Book" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.8) 10%, rgba(0,0,0,0.2) 90%), url('https://media.istockphoto.com/id/1366983105/photo/portrait-of-funny-senior-blonde-woman-in-sun-glasses-and-pink-sweater-on-white-background.jpg?s=612x612&w=0&k=20&c=j9IzY2eBsQ0m6Z7H_C7Pe4Payi2L6OHRRSBRON6krTc=');">
  <div class="container">
    <h1>Grannys are the</h1>
    <h1>best <span data-controller="typed-js"></span></h1>
    <div class="banner-buttons d-flex flex-column" data-controller="navbar"
  data-action="scroll@window->navbar#updateNavbar">
      <%= link_to "Find a grandma", grandmas_path, class: "banner-button-primary d-flex justify-content-center align-items-center mt-3 border border-2 border-primary"%>
      <% if user_signed_in? %>
      <%= link_to "My profile", user_path(current_user), class: "banner-button-secondary d-flex justify-content-center align-items-center mt-2 border border-2 border-primary" %>
     <% else %>
      <%= link_to "Create profile", new_user_registration_path, class: "banner-button-secondary d-flex justify-content-center align-items-center mt-2 border border-2 border-primary" %>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="d-flex home_cards">
    <% @grandmas.each do |grandma| %>
      <div class="main-card" id="main-card-home">
        <%= link_to grandma_path(grandma), class:"link-wrapper" do  %>
          <div class="pic-size">
            <%= cl_image_tag grandma.photo_url[0].key %>
          </div>
          <div class="card-text">
            <h2><%= "#{grandma.first_name} #{grandma.last_name} "%></h2>
            <% if grandma.description.length > 30 %>
              <p><%= "#{grandma.description[0, 50]}..."%></p>
            <% else %>
              <p><%= grandma.description %></p>
            <% end %>
          </div>
        <% end %>
      </div>
		<% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div id="navbar" class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <span><em>insta</em><strong>GRAN</strong></span>
    <% end %>

  <%= form_with url: grandmas_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find your grandma"
    %>
    <%= submit_tag "Search", class: "button-primary" %>
  <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <% if current_user.profile_photo.attached? %>
            <li class="nav-item dropdown d-flex align-items-center justify-content-center ">
              <%= link_to user_path(current_user) do %>
                <%= cl_image_tag current_user.profile_photo.key, class: "avatar" %>
              <% end %>
            </li>
          <% else %>
            <li class="nav-item dropdown d-flex align-items-center justify-content-center ">
              <%= link_to user_path(current_user) do %>
                <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png", class: "avatar" %>
              <% end %>
            </li>
          <% end %>
        <% else %>
          <li style="display: none" class= "nav-item d-flex align-items-center justify-content-center" id="login-btn">
            <%= link_to "login", "/users/sign_in", class: "nav-link" %>
          </li>
        <% end %>


                          <%# # class: "avatar dropdown-toggle",
                          # id: "navbarDropdown",
                          # data: { bs_toggle: "dropdown" },
                          # 'aria-haspopup': true,
                          # 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Browse grandmas", grandmas_path, class: "dropdown-item" %>
              <%= link_to "Create new grandma", new_grandma_path, class: "dropdown-item" %>
              <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/show.html.erb
show.html

app/views/users/show.html.erb
<div class="container p-5">
  <h1 class="fw-light mt-5">Profile</h1>
  <div class="pro-p">
      <% if current_user.profile_photo.attached? %>
            <%= cl_image_tag current_user.profile_photo.key, class: "avatar-large" %>
      <% else %>
            <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png", class: "avatar-large" %>
      <% end %>
  </div>

  <h3 class="username mt-3"><strong><%="#{@user.username}"%></strong></h3>
  <p class="address"><%="#{@user.address}"%></p>


  <div class="profile_card_wrapper mt-5 d-flex justify-content-between flex-row">
    <%# <div class="d-flex flex-column me-3" style="width: 50%">
      <div class="profile_card_granny">
        <img src="https://kitt.lewagon.com/placeholder/users/cveneziani" />
        <div class="card-product-infos ms-3">
          <h3>Granny name</h3>
          <p>Booking details</p>
        </div>
      </div>
    </div>

    <div class="d-flex flex-column ms-3" style="width: 50%">
      <div class="profile_card_granny">
        <img src="https://kitt.lewagon.com/placeholder/users/cveneziani" />
        <div class="card-product-infos ms-3">
          <h3>Granny name</h3>
          <p>Booking details</p>
        </div>
      </div>
    </div> %>

    <div class="d-flex flex-column me-3" style="width: 50%">
      <h2 class="fw-light mt-5 mb-5">My bookings:</h2>
      <% @user.bookings.each do |booking| %>
        <%= link_to grandma_path(booking.grandma), class:"link-wrapper booking-card mb-3" do  %>
          <div class="main-card">
            <div class="pic-size">
              <%= cl_image_tag booking.grandma.photo_url.first.key %>
            </div>
            <div class="card-text">
              <h3><%= "#{booking.grandma.first_name} #{booking.grandma.last_name} "%></h3>
              <p><%= "#{booking.start_time} - #{booking.end_time} "%></p>
            </div>
          <% if booking.status == "pending" %>
          <p>Your booking is not accepted yet.</p>
          <% elsif booking.status == "Accepted" %>
          <p>Your booking is accepted!</p>
          <% else %>
          <p>Your booking got rejected!</p>
          <% end %>
          <p>€<%= booking.price %></p>
          </div>
        <% end %>
      <% end %>

    </div>
  <div class="user-bookings">
    <h2 class="fw-light mt-5 mb-5">Grandma requests:</h2>
      <% @host_bookings.each do |booking| %>
        <%= link_to user_path(booking.user), class:"link-wrapper booking-card mb-3" do  %>
          <div class="main-card">
            <div class="pic-size">
              <% if booking.user.profile_photo.attached? %>
            <%= cl_image_tag booking.user.profile_photo.key, class: "avatar-large" %>
      <% else %>
            <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png", class: "avatar-large" %>
      <% end %>
            </div>
            <div class="card-text">
              <h3><%= "#{booking.user.username}"%></h3>
              <p><%= "#{booking.start_time} - #{booking.end_time} "%></p>
            </div>
            <% if booking.status == "pending" %>
            <div class="bookings-buttons">
              <%= link_to "Accept booking", booking_path(booking, booking: {status: "Accepted"}), data: {turbo_method: :patch,}, class:"button-primary"%>
              <%= link_to "Reject booking", booking_path(booking, booking: {status: "Rejected"}), data: {turbo_method: :patch,}, class:"button-primary"%>
            </div>
            <% elsif booking.status == "Accepted" %>
            <p>You accepted this booking!</p>
            <% else %>
            <p>You rejected this booking!</p>
            <% end %>
          </div>
          <% end %>
      <% end %>
  </div>
  </div>

  <%= link_to "Create a grandma", new_grandma_path, class: "button-primary"%>
  <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "button-secondary" %>
</div>